FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY . .

# Prisma client
RUN npx prisma generate

# user non-root
RUN addgroup -S appgrp && adduser -S appusr -G appgrp
USER appusr

EXPOSE 3000

CMD ["node", "server.js"]
